default_stages: [pre-commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --hook-config=--parallelism-ci-cpu-cores=1
        files: \.tf$
      - id: terraform_validate
        args:
          - --hook-config=--parallelism-ci-cpu-cores=1
        files: \.tf$
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --hook-config=--parallelism-ci-cpu-cores=1
        files: \.tf$
