version: '3'
services:
  terraform-env:
    container_name: terraform_env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        # docker/.envを作成し各変数を定義することを推奨
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        # - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - .:/workspace
    tty: true
