services:
  terraform-env:
    container_name: terraform-env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        # - AWS_DEFAULT_REGION=ap-northeast-1
        # tenvのバージョン
        - TENV_VERSION=v4.2.0-beta2
    volumes:
      - .:/iac
    tty: true
